"""
Supplemental carpark lookup table.

Loads supplemental_carparks.csv at import time and exposes:

  SUPPLEMENTAL_CARPARK_LOOKUP  — dict[normalised_name -> {name, lat, lng}]
  LTA_DEVELOPMENT_NAMES        — frozenset of normalised LTA development names
                                  (built from lta_carpark_lookup at import)

These are used by ``_fetch_supplemental_carparks`` to show carparks from
CarparkRates.csv that are not tracked by the HDB or LTA DataMall datasets.

The CSV is generated by running:
    python src/data_pipeline/geocode_rates_carparks.py

Run AFTER fetch_lta_carparks.py so LTA-covered entries are excluded from
the supplemental file.  If the CSV is absent the lookup is empty and the
backend degrades gracefully (no supplemental results shown).
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

from app.data.lta_carpark_lookup import LTA_CARPARK_LOOKUP
from app.data.lta_rates_lookup import canonicalise_name

_DATA_DIR = Path(__file__).parent
_CSV = _DATA_DIR / "supplemental_carparks.csv"


def _normalise(name: str) -> str:
    return re.sub(r"\s+", " ", name.lower().strip())


def _id_for(norm_name: str) -> str:
    """Generate a stable SUPP_ prefixed ID for a supplemental carpark."""
    return "SUPP_" + norm_name.replace(" ", "_").upper()


def _load() -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    if not _CSV.exists():
        return lookup

    with open(_CSV, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            name = row.get("name", "").strip()
            if not name:
                continue
            try:
                lookup[_normalise(name)] = {
                    "name": name,
                    "lat": float(row["lat"]),
                    "lng": float(row["lng"]),
                }
            except (ValueError, KeyError):
                continue

    return lookup


# Normalised development names from the LTA static CSV.
# Any supplemental carpark whose key is in this set is already tracked by
# LTA DataMall and must be excluded to avoid duplicate results.
LTA_DEVELOPMENT_NAMES: frozenset[str] = frozenset(
    canonicalise_name(info["development"])
    for info in LTA_CARPARK_LOOKUP.values()
    if info.get("development")
)

# Loaded once at import time
SUPPLEMENTAL_CARPARK_LOOKUP: dict[str, dict] = _load()

# Reverse map: SUPP_-prefixed ID -> normalised name key, for O(1) detail lookups.
SUPPLEMENTAL_ID_LOOKUP: dict[str, str] = {
    _id_for(norm_name): norm_name
    for norm_name in SUPPLEMENTAL_CARPARK_LOOKUP
}
